/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vksiadi;

import javax.swing.ImageIcon;
import vksiadi.telas.Tela_Dados_Membros;
import vksiadi.telas.Tela_Lista_Membros;

/**
 *
 * @author vk
 */
public class Tela_Principal extends javax.swing.JFrame {

    /**
     * Creates new form Tela_Principal
     */
    public Tela_Principal() {
        initComponents();
        
        this.setLocationRelativeTo(null);
        //SETLOGOMARCA
        ImageIcon logo = new ImageIcon(Literate.getLOGO());
        setIconImage(logo.getImage());
        nomeUsuario.setText(Literate.getMB_NOME());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nomeUsuario = new javax.swing.JLabel();
        painelCentral = new javax.swing.JScrollPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        mMembros = new javax.swing.JMenu();
        listarMembros = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        mPatrimonio = new javax.swing.JMenu();
        listarPatrimonio = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        incluirPatrimonio = new javax.swing.JMenuItem();
        mConfiguracao = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("VK_SIADI");

        mMembros.setText("Membros");

        listarMembros.setText("Listar Membros");
        listarMembros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listarMembrosActionPerformed(evt);
            }
        });
        mMembros.add(listarMembros);

        jMenuItem1.setText("Incluir Membros");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        mMembros.add(jMenuItem1);

        jMenuBar1.add(mMembros);

        mPatrimonio.setText("Patrimônio");

        listarPatrimonio.setText("Lista Patrimônio");
        mPatrimonio.add(listarPatrimonio);

        jMenuItem2.setText("Gerenciar Patrimônio");
        mPatrimonio.add(jMenuItem2);

        incluirPatrimonio.setText("Incluir Patrimônio");
        mPatrimonio.add(incluirPatrimonio);

        jMenuBar1.add(mPatrimonio);

        mConfiguracao.setText("Configurações");
        jMenuBar1.add(mConfiguracao);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(nomeUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 735, Short.MAX_VALUE))
            .addComponent(painelCentral)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(painelCentral, javax.swing.GroupLayout.DEFAULT_SIZE, 575, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nomeUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void listarMembrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listarMembrosActionPerformed
        Tela_Lista_Membros telaListaMembros = new Tela_Lista_Membros();
        this.painelCentral.setViewportView(telaListaMembros);
    }//GEN-LAST:event_listarMembrosActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        Tela_Dados_Membros telaDadosMembros = new Tela_Dados_Membros(1);
        this.painelCentral.setViewportView(telaDadosMembros);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela_Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem incluirPatrimonio;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem listarMembros;
    private javax.swing.JMenuItem listarPatrimonio;
    private javax.swing.JMenu mConfiguracao;
    private javax.swing.JMenu mMembros;
    private javax.swing.JMenu mPatrimonio;
    private javax.swing.JLabel nomeUsuario;
    public static javax.swing.JScrollPane painelCentral;
    // End of variables declaration//GEN-END:variables
}
