/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vksiadi.telas;

import java.sql.SQLException;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.text.MaskFormatter;
import pessoas.Membro;

/**
 *
 * @author Kramer
 */
public class Tela_Dados_Membros extends javax.swing.JPanel {

    /**
     * Creates new form Tela_Incluir_Membros
     */
    public Tela_Dados_Membros() {
        initComponents(); 
    }
    
    public Tela_Dados_Membros (int opcao){
        initComponents();
        
        switch(opcao){
            case 1:
                initIncluir();
                break;
            case 2:
                initCosulta();
                break;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menu = new javax.swing.JTabbedPane();
        painelDadosPessoais = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        campoCodigo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        campo_mbNome = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        campo_mbCpf = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        campo_mbSexo = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        campo_mbPai = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        campo_mbMae = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        campo_mbNacionalidade = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        campo_mbNaturalidade = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        campo_mbRgNumero = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        campo_mbRgOrgao = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        campo_mbEmail = new javax.swing.JTextField();
        salvarDadosPessoais = new javax.swing.JButton();
        editarDadosPessoais = new javax.swing.JButton();
        campo_mbDataNascimento = new javax.swing.JFormattedTextField();
        campo_mbRgData = new javax.swing.JFormattedTextField();
        painelEndereco = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        campo_EndCep = new javax.swing.JFormattedTextField();
        jLabel15 = new javax.swing.JLabel();
        campo_EndLogradouro = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        campo_EndNumero = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        campo_EndComplemento = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        campo_EndBairro = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        campo_EndCidade = new javax.swing.JTextField();
        campo_Endestado = new javax.swing.JComboBox<>();
        salvarEndereco = new javax.swing.JButton();
        editarEndereco = new javax.swing.JButton();
        painelTelefone = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        salvarTelefone = new javax.swing.JButton();
        editarTelefone = new javax.swing.JButton();
        campo_telDDD = new javax.swing.JFormattedTextField();
        campo_TelNumero = new javax.swing.JFormattedTextField();

        jLabel1.setText("Codigo:");

        jLabel2.setText("*Nome:");

        campo_mbNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                campo_mbNomeKeyReleased(evt);
            }
        });

        jLabel3.setText("CPF:");

        campo_mbCpf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                campo_mbCpfFocusGained(evt);
            }
        });
        campo_mbCpf.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                campo_mbCpfMouseClicked(evt);
            }
        });

        jLabel4.setText("*Data de Nascimento:");

        jLabel5.setText("Sexo:");

        campo_mbSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masculino", "Feminino" }));

        jLabel6.setText("Pai:");

        campo_mbPai.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                campo_mbPaiKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                campo_mbPaiKeyReleased(evt);
            }
        });

        jLabel7.setText("Mãe:");

        campo_mbMae.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                campo_mbMaeKeyReleased(evt);
            }
        });

        jLabel8.setText("*Nacionalidade:");

        campo_mbNacionalidade.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                campo_mbNacionalidadeKeyReleased(evt);
            }
        });

        jLabel9.setText("*Naturalidade:");

        campo_mbNaturalidade.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                campo_mbNaturalidadeKeyReleased(evt);
            }
        });

        jLabel10.setText("Rg:");

        jLabel11.setText("Emissor:");

        campo_mbRgOrgao.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                campo_mbRgOrgaoKeyReleased(evt);
            }
        });

        jLabel12.setText("Data:");

        jLabel13.setText("Email:");

        campo_mbEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                campo_mbEmailKeyReleased(evt);
            }
        });

        salvarDadosPessoais.setText("Salvar");
        salvarDadosPessoais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvarDadosPessoaisActionPerformed(evt);
            }
        });

        editarDadosPessoais.setText("Editar");

        campo_mbDataNascimento.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                campo_mbDataNascimentoFocusGained(evt);
            }
        });

        campo_mbRgData.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                campo_mbRgDataFocusGained(evt);
            }
        });

        javax.swing.GroupLayout painelDadosPessoaisLayout = new javax.swing.GroupLayout(painelDadosPessoais);
        painelDadosPessoais.setLayout(painelDadosPessoaisLayout);
        painelDadosPessoaisLayout.setHorizontalGroup(
            painelDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelDadosPessoaisLayout.createSequentialGroup()
                .addGroup(painelDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelDadosPessoaisLayout.createSequentialGroup()
                        .addGap(159, 159, 159)
                        .addComponent(salvarDadosPessoais)
                        .addGap(18, 18, 18)
                        .addComponent(editarDadosPessoais))
                    .addGroup(painelDadosPessoaisLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(painelDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(painelDadosPessoaisLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(campo_mbDataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(campo_mbSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(painelDadosPessoaisLayout.createSequentialGroup()
                                .addGroup(painelDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(painelDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(painelDadosPessoaisLayout.createSequentialGroup()
                                        .addComponent(campoCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(126, 126, 126)
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(campo_mbCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(campo_mbNome)))
                            .addGroup(painelDadosPessoaisLayout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(campo_mbPai))
                            .addGroup(painelDadosPessoaisLayout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(campo_mbMae))
                            .addGroup(painelDadosPessoaisLayout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(campo_mbNacionalidade, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(campo_mbNaturalidade))
                            .addGroup(painelDadosPessoaisLayout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(campo_mbEmail))
                            .addGroup(painelDadosPessoaisLayout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(campo_mbRgNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel11)
                                .addGap(7, 7, 7)
                                .addComponent(campo_mbRgOrgao, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(campo_mbRgData)))))
                .addContainerGap(125, Short.MAX_VALUE))
        );
        painelDadosPessoaisLayout.setVerticalGroup(
            painelDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelDadosPessoaisLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(painelDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(campoCodigo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(painelDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(campo_mbCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(campo_mbNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painelDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(campo_mbSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campo_mbDataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painelDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campo_mbPai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painelDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(campo_mbMae, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painelDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(campo_mbNacionalidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(campo_mbNaturalidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(painelDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(campo_mbRgNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel10))
                    .addGroup(painelDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel12)
                        .addComponent(campo_mbRgOrgao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel11)
                        .addComponent(campo_mbRgData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painelDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(campo_mbEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(painelDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(salvarDadosPessoais)
                    .addComponent(editarDadosPessoais))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        menu.addTab("Dados Pessoais", painelDadosPessoais);

        jLabel14.setText("*CEP:");

        campo_EndCep.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                campo_EndCepFocusGained(evt);
            }
        });

        jLabel15.setText("*Logradouro:");

        campo_EndLogradouro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                campo_EndLogradouroKeyReleased(evt);
            }
        });

        jLabel16.setText("*Número:");

        jLabel17.setText("Complemento:");

        campo_EndComplemento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                campo_EndComplementoKeyReleased(evt);
            }
        });

        jLabel18.setText("*Bairro:");

        campo_EndBairro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                campo_EndBairroKeyReleased(evt);
            }
        });

        jLabel19.setText("*Cidade:");

        campo_EndCidade.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                campo_EndCidadeKeyReleased(evt);
            }
        });

        campo_Endestado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO" }));

        salvarEndereco.setText("Salvar");

        editarEndereco.setText("Editar");
        editarEndereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarEnderecoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelEnderecoLayout = new javax.swing.GroupLayout(painelEndereco);
        painelEndereco.setLayout(painelEnderecoLayout);
        painelEnderecoLayout.setHorizontalGroup(
            painelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelEnderecoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(painelEnderecoLayout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campo_EndLogradouro, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(painelEnderecoLayout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campo_EndComplemento))
                    .addGroup(painelEnderecoLayout.createSequentialGroup()
                        .addGroup(painelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, painelEnderecoLayout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(campo_EndBairro))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, painelEnderecoLayout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(campo_EndNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(jLabel14)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(painelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(painelEnderecoLayout.createSequentialGroup()
                                .addComponent(campo_EndCep, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(campo_Endestado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(painelEnderecoLayout.createSequentialGroup()
                                .addComponent(jLabel19)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(campo_EndCidade))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelEnderecoLayout.createSequentialGroup()
                        .addComponent(salvarEndereco)
                        .addGap(21, 21, 21)
                        .addComponent(editarEndereco)
                        .addGap(78, 78, 78)))
                .addContainerGap(199, Short.MAX_VALUE))
        );
        painelEnderecoLayout.setVerticalGroup(
            painelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelEnderecoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(campo_EndLogradouro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(campo_EndComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(painelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(campo_EndNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(campo_EndCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campo_Endestado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(campo_EndBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19)
                    .addComponent(campo_EndCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(painelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(salvarEndereco)
                    .addComponent(editarEndereco))
                .addContainerGap(146, Short.MAX_VALUE))
        );

        menu.addTab("Endereço", painelEndereco);

        jLabel20.setText("DDD:");

        jLabel21.setText("Telefone:");

        salvarTelefone.setText("Salvar");

        editarTelefone.setText("Editar");
        editarTelefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarTelefoneActionPerformed(evt);
            }
        });

        campo_telDDD.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                campo_telDDDFocusGained(evt);
            }
        });

        campo_TelNumero.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                campo_TelNumeroFocusGained(evt);
            }
        });

        javax.swing.GroupLayout painelTelefoneLayout = new javax.swing.GroupLayout(painelTelefone);
        painelTelefone.setLayout(painelTelefoneLayout);
        painelTelefoneLayout.setHorizontalGroup(
            painelTelefoneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelTelefoneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelTelefoneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(salvarTelefone)
                    .addGroup(painelTelefoneLayout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campo_telDDD, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel21)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painelTelefoneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(editarTelefone)
                    .addComponent(campo_TelNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(289, Short.MAX_VALUE))
        );
        painelTelefoneLayout.setVerticalGroup(
            painelTelefoneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelTelefoneLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(painelTelefoneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(jLabel21)
                    .addComponent(campo_telDDD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campo_TelNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57)
                .addGroup(painelTelefoneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(salvarTelefone)
                    .addComponent(editarTelefone))
                .addContainerGap(210, Short.MAX_VALUE))
        );

        menu.addTab("Telefone", painelTelefone);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menu, javax.swing.GroupLayout.PREFERRED_SIZE, 543, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menu)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void campo_mbNomeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campo_mbNomeKeyReleased
        campo_mbNome.setText(campo_mbNome.getText().toUpperCase());
    }//GEN-LAST:event_campo_mbNomeKeyReleased

    private void campo_mbPaiKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campo_mbPaiKeyPressed
        
    }//GEN-LAST:event_campo_mbPaiKeyPressed

    private void campo_mbMaeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campo_mbMaeKeyReleased
        campo_mbMae.setText(campo_mbMae.getText().toUpperCase());
    }//GEN-LAST:event_campo_mbMaeKeyReleased

    private void campo_mbPaiKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campo_mbPaiKeyReleased
        campo_mbPai.setText(campo_mbPai.getText().toUpperCase());
    }//GEN-LAST:event_campo_mbPaiKeyReleased

    private void campo_mbNacionalidadeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campo_mbNacionalidadeKeyReleased
        campo_mbNacionalidade.setText(campo_mbNacionalidade.getText().toUpperCase());
    }//GEN-LAST:event_campo_mbNacionalidadeKeyReleased

    private void campo_mbNaturalidadeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campo_mbNaturalidadeKeyReleased
        campo_mbNaturalidade.setText(campo_mbNaturalidade.getText().toUpperCase());
    }//GEN-LAST:event_campo_mbNaturalidadeKeyReleased

    private void salvarDadosPessoaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarDadosPessoaisActionPerformed
        Membro incluirMembro = new Membro();
        
        if(!campo_mbNome.equals("") & !campo_mbDataNascimento.equals("") & !campo_mbNacionalidade.equals("") & !campo_mbNaturalidade.equals("") ){
            incluirMembro.setMb_cpf(campo_mbCpf.getText());
            incluirMembro.setMb_nome(campo_mbNome.getText());
            incluirMembro.setMb_dtNascimento(campo_mbDataNascimento.getText());
            incluirMembro.setMb_sexo(campo_mbSexo.getSelectedIndex());
            incluirMembro.setMb_pai(campo_mbPai.getText());
            incluirMembro.setMb_mae(campo_mbMae.getText());
            incluirMembro.setMb_nacionalidade(campo_mbNacionalidade.getText());
            incluirMembro.setMb_naturalidade(campo_mbNaturalidade.getText());
            incluirMembro.setMb_rgNumero(campo_mbRgNumero.getText());
            incluirMembro.setMb_rgOrgao(campo_mbRgOrgao.getText());
            incluirMembro.setMb_rgData(campo_mbRgData.getText());
            incluirMembro.setMb_email(campo_mbEmail.getText());
            try {
                incluirMembro.inserirMembro();
            } catch (SQLException ex) {
                Logger.getLogger(Tela_Dados_Membros.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else{
            JOptionPane.showMessageDialog(null, "Campos obrigatórios não preenchidos.");
        }
        
        salvarDadosPessoais.setVisible(false);
        editarDadosPessoais.setVisible(true);
        menu.setEnabledAt(1, true);
           
    }//GEN-LAST:event_salvarDadosPessoaisActionPerformed

    private void editarEnderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarEnderecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editarEnderecoActionPerformed

    private void campo_EndLogradouroKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campo_EndLogradouroKeyReleased
        campo_EndLogradouro.setText(campo_EndLogradouro.getText().toUpperCase());
    }//GEN-LAST:event_campo_EndLogradouroKeyReleased

    private void campo_EndComplementoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campo_EndComplementoKeyReleased
        campo_EndComplemento.setText(campo_EndComplemento.getText().toUpperCase());
    }//GEN-LAST:event_campo_EndComplementoKeyReleased

    private void campo_EndBairroKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campo_EndBairroKeyReleased
        campo_EndBairro.setText(campo_EndBairro.getText().toUpperCase());
    }//GEN-LAST:event_campo_EndBairroKeyReleased

    private void campo_EndCidadeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campo_EndCidadeKeyReleased
        campo_EndCidade.setText(campo_EndCidade.getText().toUpperCase());
    }//GEN-LAST:event_campo_EndCidadeKeyReleased

    private void editarTelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarTelefoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editarTelefoneActionPerformed

    private void campo_mbRgOrgaoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campo_mbRgOrgaoKeyReleased
        campo_mbRgOrgao.setText(campo_mbRgOrgao.getText().toUpperCase());
    }//GEN-LAST:event_campo_mbRgOrgaoKeyReleased

    private void campo_mbEmailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campo_mbEmailKeyReleased
       campo_mbEmail.setText(campo_mbEmail.getText().toLowerCase());
    }//GEN-LAST:event_campo_mbEmailKeyReleased

    private void campo_mbCpfMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_campo_mbCpfMouseClicked
               
    }//GEN-LAST:event_campo_mbCpfMouseClicked

    private void campo_mbCpfFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campo_mbCpfFocusGained
        try {
            MaskFormatter cpf = new MaskFormatter("###.###.###-##");
            cpf.install( campo_mbCpf);
        } catch (ParseException ex) {
            Logger.getLogger(Tela_Dados_Membros.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_campo_mbCpfFocusGained

    private void campo_mbDataNascimentoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campo_mbDataNascimentoFocusGained
        try {
            MaskFormatter dataNasc = new MaskFormatter("##/##/####");
            dataNasc.install(campo_mbDataNascimento);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_campo_mbDataNascimentoFocusGained

    private void campo_mbRgDataFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campo_mbRgDataFocusGained
        try {
            MaskFormatter dataRg = new MaskFormatter("##/##/####");
            dataRg.install(campo_mbRgData);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_campo_mbRgDataFocusGained

    private void campo_EndCepFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campo_EndCepFocusGained
        try {
            MaskFormatter cep = new MaskFormatter("##.###-###");
            cep.install(campo_EndCep);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_campo_EndCepFocusGained

    private void campo_telDDDFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campo_telDDDFocusGained
        try {
            MaskFormatter ddd = new MaskFormatter("(##)");
            ddd.install(campo_telDDD);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_campo_telDDDFocusGained

    private void campo_TelNumeroFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campo_TelNumeroFocusGained
       try {
            MaskFormatter telefone = new MaskFormatter("#####-####");
            telefone.install(campo_TelNumero);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_campo_TelNumeroFocusGained

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel campoCodigo;
    private javax.swing.JTextField campo_EndBairro;
    private javax.swing.JFormattedTextField campo_EndCep;
    private javax.swing.JTextField campo_EndCidade;
    private javax.swing.JTextField campo_EndComplemento;
    private javax.swing.JTextField campo_EndLogradouro;
    private javax.swing.JTextField campo_EndNumero;
    private javax.swing.JComboBox<String> campo_Endestado;
    private javax.swing.JFormattedTextField campo_TelNumero;
    private javax.swing.JFormattedTextField campo_mbCpf;
    private javax.swing.JFormattedTextField campo_mbDataNascimento;
    private javax.swing.JTextField campo_mbEmail;
    private javax.swing.JTextField campo_mbMae;
    private javax.swing.JTextField campo_mbNacionalidade;
    private javax.swing.JTextField campo_mbNaturalidade;
    private javax.swing.JTextField campo_mbNome;
    private javax.swing.JTextField campo_mbPai;
    private javax.swing.JFormattedTextField campo_mbRgData;
    private javax.swing.JTextField campo_mbRgNumero;
    private javax.swing.JTextField campo_mbRgOrgao;
    private javax.swing.JComboBox<String> campo_mbSexo;
    private javax.swing.JFormattedTextField campo_telDDD;
    private javax.swing.JButton editarDadosPessoais;
    private javax.swing.JButton editarEndereco;
    private javax.swing.JButton editarTelefone;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTabbedPane menu;
    private javax.swing.JPanel painelDadosPessoais;
    private javax.swing.JPanel painelEndereco;
    private javax.swing.JPanel painelTelefone;
    private javax.swing.JButton salvarDadosPessoais;
    private javax.swing.JButton salvarEndereco;
    private javax.swing.JButton salvarTelefone;
    // End of variables declaration//GEN-END:variables

        
    private void initIncluir(){
        editarDadosPessoais.setVisible(false);
        editarEndereco.setVisible(false);
        editarTelefone.setVisible(false);
        
        
        menu.setEnabledAt(1, false);
        menu.setEnabledAt(2, false);
        
    }
    
    private void initCosulta(){
        
    }
}
